services:

  auth-service:
    build:
      context: ./backend/auth-service
      dockerfile: Dockerfile
    container_name: auth
    networks:
      - transnet
    expose:
      - "4000"
    ports:
      - "4000:4000"
    env_file:
      - .env
    volumes:
      - auth-data:/app/data
      - ./ssl:/app/ssl:ro
    
  user-service:
    build:
      context: ./backend/user-service
      dockerfile: Dockerfile
    container_name: user
    networks:
      - transnet
    expose:
      - "4001"
    ports:
      - "4001:4001"
    volumes:
      - user-data:/app/data
      - user-uploads:/app/uploads
      - ./ssl:/app/ssl:ro

  chat-service:
    build:
      context: ./backend/chat-service
      dockerfile: Dockerfile
    container_name: chat
    networks:
      - transnet
    expose:
      - "4003"
    ports:
      - "4003:4003"
    volumes:
      - chat-data:/app/data
      - ./ssl:/app/ssl:ro

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - GOOGLE_CLIENT_ID=${CLIENT_ID}
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
    container_name: front
    networks:
      - transnet

networks:
  transnet:
    driver: bridge

volumes:
  auth-data:
  user-data:
  user-uploads:
  game-data:
  chat-data: 