services:

  auth-service:
    build:
      context: ./backend/auth-service
      dockerfile: Dockerfile
    container_name: auth
    networks:
      - transnet
    expose:
      - "4000"
    ports:
      - "4000:4000"
    volumes:
      - auth-data:/app/data
    
  user-service:
    build:
      context: ./backend/user-service
      dockerfile: Dockerfile
    container_name: user
    networks:
      - transnet
    expose:
      - "4001"
    ports:
      - "4001:4001"
    volumes:
      - user-data:/app/data

  # game-service:
  #   build:
  #     context: ./backend/game-service
  #     dockerfile: Dockerfile
  #   container_name: game
  #   networks:
  #     - transnet
  #   expose:
  #     - "4002"
  #   volumes:
  #     - game-data:/app/data

  # chat-service:
  #   build:
  #     context: ./backend/chat-service
  #     dockerfile: Dockerfile
  #   container_name: chat
  #   networks:
  #     - transnet
  #   expose:
  #     - "4003"
  #   volumes:
  #     - chat-data:/app/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: front
    networks:
      - transnet
    depends_on:
      - user-service
      - auth-service
      # - chat-service
      # - game-service

networks:
  transnet:
    driver: bridge

volumes:
  auth-data:
  user-data:
  # game-data:
  # chat-data: 